site_name: nteract
repo_url: https://github.com/nteract/nteract
repo_name: "GitHub"

nav:
  - Home: "index.md"
  - User Guides for Apps:
      - "Getting Started with nteract": "getting-started-with-nteract.md"
      - "Creating data visualizations in nteract": "creating-data-visualizations-in-nteract.md"
      - "nteract Desktop Keyboard Shortcuts": "kbd-shortcuts.md"
      - "Configuring the nteract desktop app": "desktop-config.md"
  - Guides for SDK Groups:
      - "Core": "./groups/core-group.md"
      - "Components": "./groups/components-group.md"
      - "Mythic": "./groups/mythic-group.md"
      - "Editors": "./groups/editors-group.md"
      - "Jupyter": "./groups/jupyter-group.md"
      - "Binder": "./groups/binder-group.md"
  - Project Resources:
      - "Data Explorer": "https://data-explorer.nteract.io"
      - "Semiotic": "https://semiotic.nteract.io"
      - "papermill": "https://papermill.readthedocs.io/en/latest/#"
      - "testbook": "https://testbook.readthedocs.io/en/latest/"
      - "Scrapbook": "https://scrapbook.readthedocs.io/en/latest/"

markdown_extensions:
  - toc:
      permalink: True
      anchorlink: True
      toc_depth: "2-3"
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - monorepo

theme:
  name: material
  