name: Continous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn
      env:
        USE_HARD_LINKS: false

    - name: Lint packages
      run: yarn run test:lint

    - name: Build all packages
      run: yarn run build:all:ci

    - name: Run tests
      run: yarn test
  
